#!/usr/bin/env python3
"""Phase 1 smoke test for the Colab-hosted Battle Lab.

The script provisions the exact Pokemon Showdown revision selected by pkmn,
validates two Regulation M-C teams, starts a private Showdown server, and runs
real websocket battles through the poke-env fork used by VGC-Bench.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import logging
import os
import platform
import re
import shutil
import signal
import socket
import subprocess
import sys
import time
from contextlib import contextmanager, suppress
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator, Sequence


PROJECT_ROOT = Path(__file__).resolve().parents[1]
FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
DEFAULT_FORMAT = "gen9championsvgc2026regmc"
DEFAULT_SHOWDOWN_REPOSITORY = "https://github.com/smogon/pokemon-showdown.git"
DEFAULT_RUNTIME_ROOT = Path("/content/battle-lab-runtime") if Path("/content").is_dir() else PROJECT_ROOT / ".battle-lab-runtime"
COMMIT_SOURCE = PROJECT_ROOT / "lib" / "champions-regulation.mjs"
COMMIT_PATTERN = re.compile(r'CHAMPIONS_SHOWDOWN_COMMIT\s*=\s*"([0-9a-f]{40})"')
RUNTIME_CONFIG_MARKER = "Generated by pkmn Battle Lab phase 1"
RUNTIME_CONFIG = f'''\
'use strict';

// {RUNTIME_CONFIG_MARKER}. This checkout is private to the Colab runtime.
exports.bindaddress = '127.0.0.1';
exports.repl = false;
exports.subprocesses = 0;
exports.watchconfig = false;
exports.backdoor = false;
exports.reportjoins = false;
exports.reportbattles = false;
exports.reportbattlejoins = false;
exports.logchat = false;
exports.logchallenges = false;
'''


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def format_duration(seconds: float | None) -> str:
    if seconds is None:
        return "--:--"
    seconds = max(0, int(seconds))
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}" if hours else f"{minutes:02d}:{seconds:02d}"


class Progress:
    """Small dependency-free progress bar with a rolling ETA."""

    def __init__(self, total: int, label: str):
        self.total = max(1, total)
        self.label = label
        self.completed = 0
        self.started_at = time.monotonic()
        self.render("Preparando")

    def render(self, detail: str) -> None:
        elapsed = time.monotonic() - self.started_at
        eta = None
        if self.completed:
            eta = elapsed / self.completed * (self.total - self.completed)
        ratio = min(1.0, self.completed / self.total)
        width = 24
        filled = round(width * ratio)
        bar = "█" * filled + "░" * (width - filled)
        print(
            f"\r{self.label} [{bar}] {self.completed}/{self.total} "
            f"· {ratio:>6.1%} · transcurrido {format_duration(elapsed)} "
            f"· ETA {format_duration(eta)} · {detail}",
            end="",
            flush=True,
        )

    def advance(self, detail: str) -> None:
        self.completed = min(self.total, self.completed + 1)
        self.render(detail)
        print()


def command_text(command: Sequence[str]) -> str:
    return " ".join(command)


def tail(path: Path, lines: int = 80) -> str:
    if not path.exists():
        return "<sin log>"
    return "\n".join(path.read_text(encoding="utf-8", errors="replace").splitlines()[-lines:])


def run_checked(
    command: Sequence[str],
    *,
    cwd: Path,
    input_text: str | None = None,
    timeout: float | None = None,
) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        list(command),
        cwd=cwd,
        input=input_text,
        text=True,
        capture_output=True,
        timeout=timeout,
        check=False,
    )
    if result.returncode:
        output = "\n".join(value.strip() for value in (result.stdout, result.stderr) if value.strip())
        raise RuntimeError(f"Falló `{command_text(command)}` (código {result.returncode}).\n{output}")
    return result


def run_checked_with_retries(
    command: Sequence[str],
    *,
    cwd: Path,
    timeout: float | None = None,
    attempts: int = 3,
) -> subprocess.CompletedProcess[str]:
    last_error: BaseException | None = None
    for attempt in range(1, attempts + 1):
        try:
            return run_checked(command, cwd=cwd, timeout=timeout)
        except (RuntimeError, subprocess.TimeoutExpired) as error:
            last_error = error
            if attempt == attempts:
                raise
            wait_seconds = 5 * attempt
            print(
                f"⚠️ `{command_text(command)}` falló; reintento "
                f"{attempt + 1}/{attempts} en {wait_seconds}s.",
                flush=True,
            )
            time.sleep(wait_seconds)
    assert last_error is not None
    raise last_error


def run_long_command(
    command: Sequence[str],
    *,
    cwd: Path,
    log_path: Path,
    label: str,
    expected_seconds: int,
) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    started = time.monotonic()
    with log_path.open("w", encoding="utf-8") as log_handle:
        process = subprocess.Popen(
            list(command),
            cwd=cwd,
            stdout=log_handle,
            stderr=subprocess.STDOUT,
            text=True,
            start_new_session=True,
        )
        try:
            while process.poll() is None:
                elapsed = time.monotonic() - started
                estimated_remaining = max(0, expected_seconds - elapsed)
                ratio = min(0.95, elapsed / max(expected_seconds, 1))
                filled = round(20 * ratio)
                bar = "█" * filled + "░" * (20 - filled)
                print(
                    f"\r{label} [{bar}] {ratio:>6.1%} · transcurrido {format_duration(elapsed)} "
                    f"· ETA estimada {format_duration(estimated_remaining)}",
                    end="",
                    flush=True,
                )
                time.sleep(1)
        except BaseException:
            if process.poll() is None:
                with suppress(ProcessLookupError):
                    os.killpg(process.pid, signal.SIGTERM)
                with suppress(subprocess.TimeoutExpired):
                    process.wait(timeout=5)
            raise
    print()
    if process.returncode:
        raise RuntimeError(
            f"Falló `{command_text(command)}` (código {process.returncode}).\n"
            f"Últimas líneas de {log_path}:\n{tail(log_path)}"
        )


def run_long_command_with_retries(
    command: Sequence[str],
    *,
    cwd: Path,
    log_path: Path,
    label: str,
    expected_seconds: int,
    attempts: int = 3,
) -> None:
    for attempt in range(1, attempts + 1):
        try:
            run_long_command(
                command,
                cwd=cwd,
                log_path=log_path,
                label=f"{label} · intento {attempt}/{attempts}",
                expected_seconds=expected_seconds,
            )
            return
        except RuntimeError:
            if attempt == attempts:
                raise
            wait_seconds = 5 * attempt
            print(f"⚠️ {label} falló; reintento en {wait_seconds}s.", flush=True)
            time.sleep(wait_seconds)


def read_showdown_commit(source: Path = COMMIT_SOURCE) -> str:
    match = COMMIT_PATTERN.search(source.read_text(encoding="utf-8"))
    if not match:
        raise RuntimeError(f"No se encontró CHAMPIONS_SHOWDOWN_COMMIT en {source}.")
    return match.group(1)


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def git_revision(path: Path) -> str | None:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=path,
        text=True,
        capture_output=True,
        check=False,
    )
    return result.stdout.strip() if result.returncode == 0 else None


def ensure_showdown_checkout(
    *,
    checkout: Path,
    repository: str,
    commit: str,
    logs_dir: Path,
) -> dict[str, Any]:
    checkout.parent.mkdir(parents=True, exist_ok=True)
    timings: dict[str, float] = {}
    fresh_clone = False
    incomplete_checkout = False

    if not (checkout / ".git").is_dir():
        if checkout.exists() and any(checkout.iterdir()):
            raise RuntimeError(f"La ruta de Showdown existe pero no es un checkout Git: {checkout}")
        fresh_clone = True
        started = time.monotonic()
        run_long_command(
            ["git", "clone", "--filter=blob:none", "--depth", "1", repository, str(checkout)],
            cwd=checkout.parent,
            log_path=logs_dir / "showdown-clone.log",
            label="Clonando Pokémon Showdown",
            expected_seconds=35,
        )
        timings["cloneSeconds"] = round(time.monotonic() - started, 3)

    # A cancelled first setup can leave the dedicated checkout with a .git
    # directory but without package.json/package-lock.json. That runtime is
    # owned by Battle Lab and can be repaired by checking out the pinned commit.
    incomplete_checkout = not (checkout / "package.json").is_file() or not (
        checkout / "package-lock.json"
    ).is_file()
    if not fresh_clone and not incomplete_checkout:
        tracked_changes = run_checked(
            ["git", "status", "--porcelain", "--untracked-files=no"],
            cwd=checkout,
        ).stdout.strip()
        if tracked_changes:
            raise RuntimeError(
                "El checkout dedicado de Showdown contiene cambios rastreados. "
                "No se modificará automáticamente; usa otra ruta de runtime."
            )

    started = time.monotonic()
    run_checked_with_retries(
        ["git", "fetch", "--depth", "1", "origin", commit],
        cwd=checkout,
        timeout=180,
    )
    if git_revision(checkout) != commit or incomplete_checkout:
        checkout_command = ["git", "checkout", "--detach"]
        if incomplete_checkout:
            checkout_command.append("--force")
        checkout_command.append(commit)
        run_checked(checkout_command, cwd=checkout, timeout=60)
    timings["checkoutSeconds"] = round(time.monotonic() - started, 3)

    lock_hash = hashlib.sha256((checkout / "package-lock.json").read_bytes()).hexdigest()
    install_marker = checkout / ".battle-lab-install.json"
    installed = False
    if install_marker.exists() and (checkout / "node_modules").is_dir():
        with suppress(json.JSONDecodeError, OSError):
            marker = json.loads(install_marker.read_text(encoding="utf-8"))
            installed = marker.get("lockHash") == lock_hash

    if not installed:
        started = time.monotonic()
        run_long_command_with_retries(
            ["npm", "ci"],
            cwd=checkout,
            log_path=logs_dir / "showdown-npm-ci.log",
            label="Instalando dependencias de Showdown",
            expected_seconds=150,
        )
        timings["npmCiSeconds"] = round(time.monotonic() - started, 3)
        install_marker.write_text(json.dumps({"lockHash": lock_hash, "installedAt": utc_now()}), encoding="utf-8")
    else:
        timings["npmCiSeconds"] = 0.0

    build_marker = checkout / ".battle-lab-build.json"
    built = False
    if build_marker.exists() and (checkout / "dist" / "sim").is_dir():
        with suppress(json.JSONDecodeError, OSError):
            marker = json.loads(build_marker.read_text(encoding="utf-8"))
            built = marker.get("commit") == commit
    if not built:
        started = time.monotonic()
        run_long_command_with_retries(
            ["npm", "run", "build"],
            cwd=checkout,
            log_path=logs_dir / "showdown-build.log",
            label="Compilando Pokémon Showdown",
            expected_seconds=35,
            attempts=2,
        )
        timings["buildSeconds"] = round(time.monotonic() - started, 3)
        build_marker.write_text(json.dumps({"commit": commit, "builtAt": utc_now()}), encoding="utf-8")
    else:
        timings["buildSeconds"] = 0.0

    actual_commit = git_revision(checkout)
    if actual_commit != commit:
        raise RuntimeError(f"Showdown quedó en {actual_commit}; se esperaba {commit}.")
    return timings


def install_runtime_config(checkout: Path) -> None:
    config_path = checkout / "config" / "config.js"
    example_path = checkout / "config" / "config-example.js"
    if config_path.exists():
        current = config_path.read_text(encoding="utf-8")
        example = example_path.read_text(encoding="utf-8") if example_path.exists() else None
        if RUNTIME_CONFIG_MARKER not in current and current != example:
            raise RuntimeError(
                f"No se reemplazará una configuración personalizada de Showdown: {config_path}. "
                "Usa el checkout dedicado creado dentro de --runtime-root."
            )
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(RUNTIME_CONFIG, encoding="utf-8")


def validate_team(checkout: Path, battle_format: str, team: str) -> str:
    result = run_checked(
        ["node", "pokemon-showdown", "validate-team", battle_format],
        cwd=checkout,
        input_text=team,
        timeout=60,
    )
    return result.stdout.strip()


def verify_illegal_team_is_rejected(checkout: Path, battle_format: str, team: str) -> str:
    illegal_team, replacements = re.subn(
        r"EVs:\s*\d+\s+(HP|Atk|Def|SpA|SpD|Spe)",
        lambda match: f"EVs: 33 {match.group(1)}",
        team,
        count=1,
    )
    if replacements != 1:
        raise RuntimeError("No fue posible construir el control negativo de Stat Points.")
    result = subprocess.run(
        ["node", "pokemon-showdown", "validate-team", battle_format],
        cwd=checkout,
        input=illegal_team,
        text=True,
        capture_output=True,
        timeout=60,
        check=False,
    )
    output = "\n".join(value.strip() for value in (result.stdout, result.stderr) if value.strip())
    if result.returncode == 0:
        raise RuntimeError("Showdown aceptó el equipo deliberadamente ilegal (33 Stat Points en un stat).")
    if "more than 32 Stat Points" not in output:
        raise RuntimeError(f"El control negativo falló por un motivo inesperado:\n{output}")
    return output


def port_is_open(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as connection:
        connection.settimeout(0.25)
        return connection.connect_ex(("127.0.0.1", port)) == 0


@dataclass
class ShowdownServer:
    process: subprocess.Popen[str]
    log_path: Path
    startup_seconds: float


@contextmanager
def running_showdown(checkout: Path, port: int, log_path: Path, timeout: float = 90) -> Iterator[ShowdownServer]:
    if port_is_open(port):
        raise RuntimeError(f"El puerto {port} ya está ocupado; no se terminará un proceso ajeno.")
    log_path.parent.mkdir(parents=True, exist_ok=True)
    started = time.monotonic()
    log_handle = log_path.open("w", encoding="utf-8")
    process = subprocess.Popen(
        ["node", "pokemon-showdown", "start", str(port), "--no-security"],
        cwd=checkout,
        stdout=log_handle,
        stderr=subprocess.STDOUT,
        text=True,
        start_new_session=True,
    )
    try:
        while time.monotonic() - started < timeout:
            if process.poll() is not None:
                raise RuntimeError(f"Showdown terminó durante el arranque.\n{tail(log_path)}")
            if port_is_open(port):
                yield ShowdownServer(process, log_path, round(time.monotonic() - started, 3))
                return
            time.sleep(0.25)
        raise TimeoutError(f"Showdown no abrió el puerto {port} en {timeout:.0f}s.\n{tail(log_path)}")
    finally:
        if process.poll() is None:
            with suppress(ProcessLookupError):
                process.send_signal(signal.SIGINT)
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                with suppress(ProcessLookupError):
                    os.killpg(process.pid, signal.SIGTERM)
                try:
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    with suppress(ProcessLookupError):
                        os.killpg(process.pid, signal.SIGKILL)
                    process.wait(timeout=5)
        log_handle.close()


def battle_summary(battle: Any, duration_seconds: float, player_a: str, player_b: str) -> dict[str, Any]:
    if battle.won:
        winner = player_a
    elif battle.lost:
        winner = player_b
    else:
        winner = "tie"
    return {
        "battleTag": battle.battle_tag,
        "winner": winner,
        "turns": battle.turn,
        "durationSeconds": round(duration_seconds, 3),
    }


async def run_battles(
    *,
    port: int,
    battle_format: str,
    team_a: str,
    team_b: str,
    count: int,
    timeout: float,
    replay_dir: Path,
) -> tuple[list[dict[str, Any]], dict[str, int]]:
    try:
        from poke_env import AccountConfiguration, ServerConfiguration
        from poke_env.player import MaxBasePowerPlayer, RandomPlayer
    except ImportError as error:
        raise RuntimeError(
            "Falta poke-env. Instala battle_lab/requirements-phase1.txt antes de ejecutar el smoke test."
        ) from error

    suffix = hashlib.sha256(f"{time.time_ns()}".encode()).hexdigest()[:6]
    server_configuration = ServerConfiguration(
        f"ws://127.0.0.1:{port}/showdown/websocket",
        "https://play.pokemonshowdown.com/action.php?",
    )
    common = {
        "battle_format": battle_format,
        "server_configuration": server_configuration,
        "max_concurrent_battles": 1,
        "accept_open_team_sheet": True,
        "log_level": logging.WARNING,
    }
    player_a = MaxBasePowerPlayer(
        account_configuration=AccountConfiguration(f"BLAlpha{suffix}", None),
        team=team_a,
        save_replays=str(replay_dir),
        **common,
    )
    player_b = RandomPlayer(
        account_configuration=AccountConfiguration(f"BLBeta{suffix}", None),
        team=team_b,
        **common,
    )

    summaries: list[dict[str, Any]] = []
    progress = Progress(count, "Combates WebSocket")
    try:
        for index in range(count):
            previous_tags = set(player_a.battles)
            started = time.monotonic()
            await asyncio.wait_for(player_a.battle_against(player_b, n_battles=1), timeout=timeout)
            new_tags = set(player_a.battles) - previous_tags
            if len(new_tags) != 1:
                raise RuntimeError(f"Se esperaba una batalla nueva y se recibieron {len(new_tags)}: {sorted(new_tags)}")
            battle = player_a.battles[new_tags.pop()]
            if not battle.finished:
                raise RuntimeError(f"La batalla {battle.battle_tag} no terminó.")
            summaries.append(
                battle_summary(
                    battle,
                    time.monotonic() - started,
                    player_a.username,
                    player_b.username,
                )
            )
            progress.advance(f"Batalla {index + 1} terminada")
    finally:
        with suppress(Exception):
            await player_a.ps_client.stop_listening()
        with suppress(Exception):
            await player_b.ps_client.stop_listening()

    wins = {
        "alpha": sum(summary["winner"] == player_a.username for summary in summaries),
        "beta": sum(summary["winner"] == player_b.username for summary in summaries),
        "ties": sum(summary["winner"] == "tie" for summary in summaries),
    }
    return summaries, wins


def environment_snapshot(server_pid: int | None = None) -> dict[str, Any]:
    try:
        import psutil
    except ImportError:
        psutil = None

    snapshot: dict[str, Any] = {
        "platform": platform.platform(),
        "python": platform.python_version(),
        "node": run_checked(["node", "--version"], cwd=PROJECT_ROOT).stdout.strip(),
        "npm": run_checked(["npm", "--version"], cwd=PROJECT_ROOT).stdout.strip(),
        "cpuCount": os.cpu_count(),
    }
    if psutil is not None:
        memory = psutil.virtual_memory()
        snapshot["memoryTotalBytes"] = memory.total
        snapshot["memoryAvailableBytes"] = memory.available
        if server_pid is not None:
            rss_bytes = 0
            processes = []
            with suppress(psutil.Error):
                server_process = psutil.Process(server_pid)
                processes.append(server_process)
                with suppress(psutil.Error):
                    processes.extend(server_process.children(recursive=True))
            for process in processes:
                with suppress(psutil.Error):
                    if process.is_running():
                        rss_bytes += process.memory_info().rss
            snapshot["showdownRssBytes"] = rss_bytes or None
    nvidia_smi = shutil.which("nvidia-smi")
    if nvidia_smi:
        result = subprocess.run(
            [nvidia_smi, "--query-gpu=name,memory.total", "--format=csv,noheader"],
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode == 0:
            snapshot["gpu"] = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    return snapshot


def atomic_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime-root", type=Path, default=DEFAULT_RUNTIME_ROOT)
    parser.add_argument("--results-dir", type=Path, default=None)
    parser.add_argument("--showdown-checkout", type=Path, default=None)
    parser.add_argument("--showdown-repository", default=DEFAULT_SHOWDOWN_REPOSITORY)
    parser.add_argument("--showdown-commit", default=None)
    parser.add_argument("--skip-setup", action="store_true")
    parser.add_argument("--format", default=DEFAULT_FORMAT)
    parser.add_argument("--team-a", type=Path, default=FIXTURES_DIR / "mc_team_alpha.txt")
    parser.add_argument("--team-b", type=Path, default=FIXTURES_DIR / "mc_team_beta.txt")
    parser.add_argument("--battles", type=int, default=20)
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--battle-timeout", type=float, default=180)
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    if args.battles < 1:
        raise SystemExit("--battles debe ser mayor que cero.")
    if not 1 <= args.port <= 65535:
        raise SystemExit("--port debe estar entre 1 y 65535.")
    missing_commands = [command for command in ("git", "node", "npm") if shutil.which(command) is None]
    if missing_commands:
        raise RuntimeError(
            "Faltan comandos requeridos por Battle Lab: " + ", ".join(missing_commands) + "."
        )

    runtime_root = args.runtime_root.resolve()
    results_dir = (args.results_dir or runtime_root / "results").resolve()
    run_id = datetime.now(timezone.utc).strftime("phase1-%Y%m%dT%H%M%S-%fZ")
    run_root = runtime_root / "runs" / run_id
    logs_dir = run_root / "logs"
    local_replays = run_root / "replays"
    local_replays.mkdir(parents=True, exist_ok=True)
    commit = args.showdown_commit or read_showdown_commit()
    team_a = args.team_a.resolve().read_text(encoding="utf-8").strip() + "\n"
    team_b = args.team_b.resolve().read_text(encoding="utf-8").strip() + "\n"
    showdown_checkout = (args.showdown_checkout or runtime_root / "pokemon-showdown").resolve()
    overall = Progress(6, "Fase 1")
    started = time.monotonic()
    if args.skip_setup:
        if git_revision(showdown_checkout) != commit:
            raise RuntimeError(
                f"--skip-setup requiere Showdown en {commit}; "
                f"el checkout está en {git_revision(showdown_checkout)}."
            )
        if not (showdown_checkout / "node_modules").is_dir() or not (showdown_checkout / "dist" / "sim").is_dir():
            raise RuntimeError("--skip-setup requiere dependencias instaladas y Showdown compilado.")
        setup_timings = {"skipped": True}
    else:
        setup_timings = ensure_showdown_checkout(
            checkout=showdown_checkout,
            repository=args.showdown_repository,
            commit=commit,
            logs_dir=logs_dir,
        )
    install_runtime_config(showdown_checkout)
    overall.advance("Showdown fijado y compilado")

    validation_a = validate_team(showdown_checkout, args.format, team_a)
    validation_b = validate_team(showdown_checkout, args.format, team_b)
    overall.advance("Dos equipos M-C válidos")

    negative_validation = verify_illegal_team_is_rejected(showdown_checkout, args.format, team_a)
    overall.advance("Control ilegal rechazado correctamente")

    with running_showdown(showdown_checkout, args.port, logs_dir / "showdown-server.log") as server:
        overall.advance(f"Servidor privado listo en 127.0.0.1:{args.port}")
        battle_started = time.monotonic()
        battles, wins = asyncio.run(
            run_battles(
                port=args.port,
                battle_format=args.format,
                team_a=team_a,
                team_b=team_b,
                count=args.battles,
                timeout=args.battle_timeout,
                replay_dir=local_replays,
            )
        )
        resources = environment_snapshot(server.process.pid)
        startup_seconds = server.startup_seconds
        battle_seconds = time.monotonic() - battle_started
    server_log = (logs_dir / "showdown-server.log").read_text(encoding="utf-8", errors="replace")
    if "CRASH:" in server_log:
        raise RuntimeError(f"Showdown registró un fallo interno durante el smoke test.\n{tail(logs_dir / 'showdown-server.log')}")
    overall.advance(f"{len(battles)} combates WebSocket terminados")

    shutil.copytree(logs_dir, local_replays / "logs", dirs_exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)
    replay_archive = Path(
        shutil.make_archive(str(results_dir / f"{run_id}-replays"), "zip", root_dir=local_replays)
    )
    result_path = results_dir / f"{run_id}.json"
    total_seconds = time.monotonic() - started
    payload = {
        "schemaVersion": 1,
        "runId": run_id,
        "createdAt": utc_now(),
        "status": "passed",
        "projectCommit": git_revision(PROJECT_ROOT),
        "showdown": {
            "repository": args.showdown_repository,
            "commit": commit,
            "format": args.format,
            "port": args.port,
            "startupSeconds": startup_seconds,
            "setupTimings": setup_timings,
        },
        "teams": {
            "alpha": {
                "path": str(args.team_a.resolve()),
                "sha256": sha256_text(team_a),
                "validation": {"status": "valid", "message": validation_a or None},
            },
            "beta": {
                "path": str(args.team_b.resolve()),
                "sha256": sha256_text(team_b),
                "validation": {"status": "valid", "message": validation_b or None},
            },
            "negativeControl": negative_validation,
        },
        "battles": {
            "requested": args.battles,
            "completed": len(battles),
            "durationSeconds": round(battle_seconds, 3),
            "battlesPerMinute": round(len(battles) / battle_seconds * 60, 3),
            "wins": wins,
            "items": battles,
        },
        "environment": resources,
        "artifacts": {"replaysZip": str(replay_archive)},
        "totalDurationSeconds": round(total_seconds, 3),
    }
    atomic_json(result_path, payload)
    overall.advance(f"Resultado persistido en {result_path}")

    print("\n✅ Fase 1 superada")
    print(f"   Formato: {args.format}")
    print(f"   Combates: {len(battles)}/{args.battles}")
    print(f"   Rendimiento: {payload['battles']['battlesPerMinute']} combates/min")
    print(f"   Resultado: {result_path}")
    print(f"   Replays: {replay_archive}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nInterrumpido por el usuario; el servidor fue detenido.", file=sys.stderr)
        raise SystemExit(130)
